### ISSUE TITLE
depricated?

### ISSUE THREAD

**Issue by dareksob** [Pandawan/deno_notify#13]
I get with the basic example in powershell this; Deno dont supprt dlopen anymore since deno 1.25.x or earlier

error: Uncaught (in promise) TypeError: Deno.dlopen is not a function

**Comment by Pandawan** [comment]
Hey, thanks for letting me know. 
I'll try and update it for 1.25+ soon, maybe within the next week or so. 
Sorry about that.

**Comment by Pandawan** [comment]
I believe the most recent commit (https://github.com/Pandawan/deno_notify/commit/89ed931c17a68fcefc29349b750dabcd84e69efa) should fix this.
Please try v1.4.0 and let me know if you get any issues.

**Comment by joost-de-vries** [comment]
I'm getting the same error for `1.4.2`: "Deno.dlopen is not a function"
I'm on deno `1.31.1`

**Comment by Pandawan** [comment]
@joost-de-vries So the error "Deno.dlopen is not a function" actually occurs because you did not add the `--unstable` flag when running your code. This library requires ffi's to work, which have not yet been stabilized by Deno, so you need to use this flag to explicitly tell Deno to allow the ffi API.

Seeing as this isn't the first time people mention this issue, I've added a section in the FAQ to address this.

Anyway, I also noticed that Deno 1.31 also added breaking changes to their FFI API so I'm releasing a new update (0d3dc10) to fix this. Should be v1.4.3.
