### ISSUE TITLE
Could not obtain symbol from the Library error

### ISSUE THREAD

**Issue by joshatoutthink** [Pandawan/deno_notify#5]
When I tried to use the library I get this message. 

```sh
error: Uncaught Error: Could not obtain symbol from the library: dlsym(0x7fc7e8531920, init): symbol not found
Deno.openPlugin("./libdeno_notify.dylib");
     ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.openPlugin (deno:runtime/js/40_plugins.js:8:22)
    at file:///Users/joshkennedy00/sites/joshs/time-to-harvest/deno/test.ts:3:6
```

This happens both when I install the plugin locally and use the prepared endpoint.
 
Here is the code that I am running that causes the bug   

```ts
import { notify } from "https://deno.land/x/deno_notify@0.4.5/ts/mod.ts";

Deno.openPlugin("./libdeno_notify.dylib");
const sendAlert = () =>
  notify({
    title: "TEST",
    message: "testing os notification",
  });

sendAlert();
```

**Comment by Pandawan** [comment]
Yeah, unfortunately Deno has removed support for plugins because they were too unstable and caused many issues. This means that this plugin will not work with current versions of Deno. However, [a new FFI system is in the works](https://deno.com/blog/v1.13#experimental-ffi-replaces-native-plugin-system) which should allow me to continue this project. Once [support for strings/buffers is added](https://github.com/denoland/deno/pull/11648/), I’ll be able to start work again on this. Sorry for the inconvenience.
